<a href="https://colab.research.google.com/github/Marcus-Borges/Python-com-Pandas/blob/main/Analise_dados_c_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importando o Pandas
import pandas as pd

In [3]:
# Importanto planilha de testes
from google.colab import files 
uploaded = files.upload()

Saving Pasta1.xlsx to Pasta1.xlsx

In [4]:
# Para saber qual arquivo carregamos
for fn in uploaded.keys():   
  print('Arquivo "{name}" com tamanho de {length} bytes'.format(name=fn, length=len(uploaded[fn])))

Arquivo "Pasta1.xlsx" com tamanho de 8825 bytes

In [5]:
# Preparar o arquivo para leitura
Pasta1 = pd.read_excel('Pasta1.xlsx')

In [19]:
# Para conhecer um pouco sobre o arquivo aberto - O “shape” que mostra uma tupla com o número de linhas e colunas do arquivo
print(Pasta1.shape)

(10, 2)

In [20]:
# Para conhecer um pouco sobre o arquivo aberto - O “head” mostra  os primeiros 5 registros do dataset, mas se você passar a quantidade de registros ele apresentará a quantidade solicitada, 
# por exemplo 8 (Exemplo seguinte)
display(Pasta1.head())

   números letras
0        1      a
1        2      b
2        3      c
3        4      d
4        5      e

In [21]:
display(Pasta1.head(8))

   números letras
0        1      a
1        2      b
2        3      c
3        4      d
4        5      e
5        6      f
6        7      g
7        8      h

Trabalhando base de dados Census.csv

In [16]:
# Carregando Database
uploaded.update(files.upload())

Saving basecensus.csv to basecensus.csv

In [17]:
# Carregado arquivo - basecensus.csv
dados2 = pd.read_csv('basecensus.csv')

In [18]:
# Comando Dataframe.shape e Dataframe.describe()
print(dados2.shape)
# Mostra o número de linhas e colunas (linhas, colunas)

# Só as linhas
print(dados2.shape[0])

(30162, 16)
30162

In [33]:
display(dados2.head(16))

,Unnamed: 0,age,workclass,final.weight,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loos,hour.per.week,native.country,income
0,1,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,2,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,3,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,4,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,5,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,6,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,7,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,8,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,9,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,10,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,11,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,12,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
12,13,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
13,14,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
14,16,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
15,17,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K

In [24]:
# Quais são as colunas e que tipo de dados cada um tem.
print(dados2.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30162 entries, 0 to 30161
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      30162 non-null  int64
 1   age             30162 non-null  int64
 2   workclass       30162 non-null  object
 3   final.weight    30162 non-null  int64
 4   education       30162 non-null  object
 5   education.num   30162 non-null  int64
 6   marital.status  30162 non-null  object
 7   occupation      30162 non-null  object
 8   relationship    30162 non-null  object
 9   race            30162 non-null  object
 10  sex             30162 non-null  object
 11  capital.gain    30162 non-null  int64
 12  capital.loos    30162 non-null  int64
 13  hour.per.week   30162 non-null  int64
 14  native.country  30162 non-null  object
 15  income          30162 non-null  object
dtypes: int64(7), object(9)
memory usage: 3.7+ MB
None

In [25]:
# describe() mostra as estatisticas "mais básicas" que a gente precisa
print(dados2.describe())

         Unnamed: 0           age  final.weight  education.num  capital.gain  \
count  30162.000000  30162.000000  3.016200e+04   30162.000000  30162.000000
mean   16288.103242     38.437902  1.897938e+05      10.121312   1092.007858
std     9383.401676     13.134665  1.056530e+05       2.549995   7406.346497
min        1.000000     17.000000  1.376900e+04       1.000000      0.000000
25%     8179.250000     28.000000  1.176272e+05       9.000000      0.000000
50%    16286.500000     37.000000  1.784250e+05      10.000000      0.000000
75%    24402.750000     47.000000  2.376285e+05      13.000000      0.000000
max    32561.000000     90.000000  1.484705e+06      16.000000  99999.000000

       capital.loos  hour.per.week
count  30162.000000   30162.000000
mean      88.372489      40.931238
std      404.298370      11.979984
min        0.000000       1.000000
25%        0.000000      40.000000
50%        0.000000      40.000000
75%        0.000000      45.000000
max     4356.000000      99.000000

In [26]:
# Filtrar apenas por uma coluna
display(dados2['education'])

0          Bachelors
1          Bachelors
2            HS-grad
3               11th
4          Bachelors
            ...
30157     Assoc-acdm
30158        HS-grad
30159        HS-grad
30160        HS-grad
30161        HS-grad
Name: education, Length: 30162, dtype: object

In [27]:
# Criando um novo dataframe com colunas mais específicas.
dados3 = dados2[['age', 'workclass', 'occupation', 'sex']]
display(dados3)

       age          workclass          occupation      sex
0       39          State-gov        Adm-clerical     Male
1       50   Self-emp-not-inc     Exec-managerial     Male
2       38            Private   Handlers-cleaners     Male
3       53            Private   Handlers-cleaners     Male
4       28            Private      Prof-specialty   Female
...    ...                ...                 ...      ...
30157   27            Private        Tech-support   Female
30158   40            Private   Machine-op-inspct     Male
30159   58            Private        Adm-clerical   Female
30160   22            Private        Adm-clerical     Male
30161   52       Self-emp-inc     Exec-managerial   Female

[30162 rows x 4 columns]

In [32]:
# Utiliznado o describe() para mostrar média de idade ('age') no df criado anteriormente ('dados3')
print(dados3.describe())

                age
count  30162.000000
mean      38.437902
std       13.134665
min       17.000000
25%       28.000000
50%       37.000000
75%       47.000000
max       90.000000

In [36]:
dados4 = dados3[['age', 'sex']].groupby(by='sex').mean().round(2)
display(dados4)

           age
sex
 Female  36.88
 Male    39.18